### ISSUE TITLE
Link to invoice-api-doc looks dead

### ISSUE THREAD

**Issue by satoryu** [moneyforward/mf_cloud-invoice-ruby#5]
The header of this repository has a link to the doc: invoice-api-doc but it says 404. 
Has the repository 'invoice-api-doc' gone? 

<img width="772" alt="Screen_Shot_2019-09-10_at_8_41_56" src="https://user-images.githubusercontent.com/124871/64573635-f762f400-d3a6-11e9-8616-6863b532fbe5.png">

**Comment by satoryu** [comment]
There are same issues in README.md: 
https://github.com/moneyforward/mf_cloud-invoice-ruby/blame/master/README.md

**Comment by akira-hamada** [comment]
@satoryu Thanks for your PR. We're fixing the wrong link url. 👍

**Comment by akira-hamada** [comment]
Close this issue because We've fixed the url. Thanks for your reporting 👍

**Comment by akira-hamada** [comment]
I've missed need to fix repo description 😅

**Comment by 3150** [comment]
This is because the target repository has been private archived 😓

**Comment by ShuheiGoto** [comment]
@satoryu 
We deleted wrong link for API document in repo description.

If you need API document, Please, check https://invoice.moneyforward.com/api/v2/swagger_ui

Thanks for your reporting.
